---
- name: RADIUS | Copy radius server file
  copy:
    src: "radius-server/{{ item }}"
    dest: "{{ radius_server_dir }}/"
    mode: 0755
    owner: root
    group: root
  with_items:
    - default
    - radiusd.conf
    - eap

- name: RADIUS | Copy radius server sql file
  template:
    src: radius-server-sql.j2
    dest: "{{ radius_server_dir }}/sql"
    mode: 0755
    owner: root
    group: root

- name: RADIUS | Copy radius server users file
  template:
    src: radius-server-users.j2
    dest: "{{ radius_server_dir }}/users"
    mode: 0755
    owner: root
    group: root

- name: RADIUS | Copy radius server client config file
  template:
    src: radius-server-clientconf.j2
    dest: "{{ radius_server_dir }}/clients.conf"
    mode: 0755
    owner: root
    group: root

- name: RADIUS | Copy radius server proxy config file
  template:
    src: radius-server-proxyconf.j2
    dest: "{{ radius_server_dir }}/proxy.conf"
    mode: 0755
    owner: root
    group: root

- name: RADIUS | Pull radius server images
  shell: "docker pull {{ radiusServerImage }}"

- name: RADIUS | Run radius server container
  shell: "docker run -d --restart always --name radius-server -p {{ proxy.backend.port }}:1812/udp -v {{ item }}/users:/etc/freeradius/users -v {{ item }}/clients.conf:/etc/freeradius/clients.conf -v {{ item }}/proxy.conf:/etc/freeradius/proxy.conf -v {{ item }}/radiusd.conf:/etc/freeradius/radiusd.conf -v {{ item }}/eap:/etc/raddb/mods-enabled/eap -v {{ item }}/default:/etc/raddb/sites-enabled/default -v {{ item }}/sql:/etc/raddb/mods-enabled/sql {{ radiusServerImage }} \"-X\""
  with_items:
    - "{{ radius_server_dir }}"
