---
- name: Radius | Check yum.repos.d exists
  stat: path=/etc/yum.repos.d
  register: repos_stat

- name: Radius | Backup yum.repos.d
  command: mv -f --backup=numbered /etc/yum.repos.d /etc/yum.repos.d.installer
  when: repos_stat.stat.exists
  ignore_errors: yes

- name: Radius | Create yum.repos.d
  file:
    path: /etc/yum.repos.d/
    state: directory

- name: Radius | Add kylincloud repo
  yum_repository:
    name: kylincloud
    description: registry.kylincloud.org repo in deploy
    file: kylincloud
    gpgcheck: no
    baseurl: "{{ baseurl }}"
    enabled: yes