---
## 非使用客户提供的NFS服务场景时
- name: NFS-reset | Remove file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nfs_dir }}"
    - /etc/exports
  when: not nfs_exist

- name: NFS-reset | Stop rpcbind service
  service:
    name: rpcbind
    state: stopped
  failed_when: false
  when: not nfs_exist

- name: NFS-reset | Stop nfs-server service
  service:
    name: nfs-server
    state: stopped
  failed_when: false
  when: not nfs_exist

- name: NFS | Create nfs directory if they don't exist
  file:
    path: "{{ nfs_dir }}"
    state: directory
    mode: 0775
  when: nfs_exist